apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: redhat
    repository: oci://ghcr.io/refaelsitbon/helm
    version: 1.0.0
    alias: deploy1
  - name: redhat
    repository: oci://ghcr.io/refaelsitbon/helm
    version: 1.0.0
    alias: deploy2
version: 1.0.0
appVersion: "1.0.0"
